server:
  port: 2001

spring:
  application:
    name: order-service

# nacos 注册中心地址
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848







 #数据源配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/seata_order?useUnicode=true&characterEncoding=UTF-8&characterSetResults=UTF-8&zeroDateTimeBehavior=convertToNull
    username: root
    password: rootroot


logging:
  level:
    io:
      seata: debug

