server:
  port: 7006


#由于要使用actuator，所以必须要将安全全县关闭-->
management:
  security:
    enabled: false

#  cloud:
#    config:
#      profile: dev
#      discovery:
#        enabled: true
#        service-id: config-server

spring:
  application:
    name: cloud-config-client


eureka:
  client:
    #表示是否将自己注册进EurekaServer默认为true
    register-with-eureka: true
    #是否从EurekaServer抓取已有的注册消息，默认为true，单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8761/eureka/