server:
  port: 7008

spring:
  application:
    name: congfig-server-7008


eureka:
  client:
    #表示是否将自己注册进EurekaServer默认为true
    register-with-eureka: true
    #是否从EurekaServer抓取已有的注册消息，默认为true，单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8761/eureka/

  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/lihewei/spring-cloud-repo
